import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'
import router from './router'
import './assets/main.css'
// Flowbite JS interactivity (dropdowns, modals, etc.)
// CSS is generated by the Tailwind plugin — do not import flowbite.css separately
import 'flowbite'

const app = createApp(App)

app.use(createPinia())
app.use(router)

app.mount('#app')
